// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { HelmetProvider } from 'E:/dynamic-thread-pool-master (3)/dynamic-thread-demo/dynamic-thread-pool-7518-banchengkemeng-main/dynamic-thread-pool-web-frontend/node_modules/@umijs/renderer-react';
import { context } from './helmetContext';

export const innerProvider = (container) => {
  return React.createElement(HelmetProvider, { context }, container);
}
