server:
  port: 8091

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 动态线程池配置
dynamic-thread-pool:
  registry:
    redis:
      host: localhost
      port: 6379
    report-cron: "0/10 * * * * ?"
  web:
    auth:
      enable: false
      username: bread
      password: bread
    context-path: /dtp
    enabled: true
    grafana-dashboard-url: http://localhost:3000/d/cdvvy9felux34e/e58aa8-e68081-e7babf-e7a88b-e6b1a0-e79b91-e68ea7?orgId=2&from=2024-11-25T02:34:39.923Z&to=2024-11-25T08:34:39.924Z&timezone=browser&var-applicationName=dynamic-thread-pool-test&var-poolName=threadPoolExecutor01&refresh=5s
  alarm:
    enabled: true
    access-token:
      ding-ding: 586cb499795791acf61a20977c4cc2d76cf941f3777fa1d75240b12f3ba5de0e
    use-platform:
      - "DingDing"
